version: '3'
services:
  app:
    container_name: vandyahmad_gotoko
    build: .
    ports: 
      - 3030:3030 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - mysql           
    networks:
      - fullstack
  mysql:
    image: mysql:5.7
    container_name: full_db_mysql
    ports: 
      - ${MYSQL_PORT}:${MYSQL_PORT}
    environment: 
      - MYSQL_ROOT_HOST=${MYSQL_HOST} 
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DBNAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - fullstack
  
volumes:
  api:
  database_mysql:
networks:
  fullstack:
    driver: bridge